<?xml version="1.0" ?>
<!DOCTYPE imdb [
        <!ELEMENT imdb (movie|director|actor)*>
        <!ELEMENT movie (year|title|genres|director-ref|actor-ref)*>
        <!ATTLIST movie
                id CDATA #REQUIRED>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT genres (genre)*>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT director-ref (#PCDATA)>
        <!ATTLIST director-ref
                id CDATA #REQUIRED>
        <!ELEMENT actor-ref (#PCDATA)>
        <!ATTLIST actor-ref
                id CDATA #REQUIRED>
        <!ELEMENT director (name|dob)*>
        <!ATTLIST director
                id CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT dob (#PCDATA)>
        <!ELEMENT actor (name|dob)*>
        <!ATTLIST actor
                id CDATA #REQUIRED>
        ]>
<imdb>
  <movie id="/title/tt8503618/">
    <year>2020</year>
    <title>Hamilton</title>
    <genres>
      <genre>Biography</genre>
      <genre>Drama</genre>
      <genre>History</genre>
    </genres>
    <director-ref id="/name/nm2371802/"/>
    <actor-ref id="/name/nm0592135/"/>
    <actor-ref id="/name/nm5623883/"/>
    <actor-ref id="/name/nm1502434/"/>
    <actor-ref id="/name/nm0325989/"/>
  </movie>
  <director id="/name/nm2371802/">
    <name>Thomas Kail</name>
    <dob/>
  </director>
  <actor id="/name/nm0592135/">
    <name>Lin-Manuel Miranda</name>
    <dob>1980-1-16</dob>
  </actor>
  <actor id="/name/nm5623883/">
    <name>Phillipa Soo</name>
    <dob>1990-5-31</dob>
  </actor>
  <actor id="/name/nm1502434/">
    <name>Leslie Odom Jr.</name>
    <dob>1981-8-6</dob>
  </actor>
  <actor id="/name/nm0325989/">
    <name>Ren√©e Elise Goldsberry</name>
    <dob>1971-1-2</dob>
  </actor>
  <movie id="/title/tt7146812/">
    <year>I</year>
    <title>Onward</title>
    <genres>
      <genre>Animation</genre>
      <genre>Adventure</genre>
      <genre>Comedy</genre>
    </genres>
    <director-ref id="/name/nm0768959/"/>
    <actor-ref id="/name/nm4043618/"/>
    <actor-ref id="/name/nm0695435/"/>
    <actor-ref id="/name/nm0000506/"/>
    <actor-ref id="/name/nm0818055/"/>
  </movie>
  <director id="/name/nm0768959/">
    <name>Dan Scanlon</name>
    <dob>1976-6-21</dob>
  </director>
  <actor id="/name/nm4043618/">
    <name>Tom Holland</name>
    <dob>1996-6-1</dob>
  </actor>
  <actor id="/name/nm0695435/">
    <name>Chris Pratt</name>
    <dob>1979-6-21</dob>
  </actor>
  <actor id="/name/nm0000506/">
    <name>Julia Louis-Dreyfus</name>
    <dob>1961-1-13</dob>
  </actor>
  <actor id="/name/nm0818055/">
    <name>Octavia Spencer</name>
    <dob>1972-5-25</dob>
  </actor>
  <movie id="/title/tt9686708/">
    <year>2020</year>
    <title>The King of Staten Island</title>
    <genres>
      <genre>Comedy</genre>
      <genre>Drama</genre>
    </genres>
    <director-ref id="/name/nm0031976/"/>
    <actor-ref id="/name/nm0203457/"/>
    <actor-ref id="/name/nm2525790/"/>
    <actor-ref id="/name/nm6618353/"/>
    <actor-ref id="/name/nm7868231/"/>
  </movie>
  <director id="/name/nm0031976/">
    <name>Judd Apatow</name>
    <dob>1967-12-6</dob>
  </director>
  <actor id="/name/nm0203457/">
    <name>Pete Davidson</name>
    <dob>1993-11-16</dob>
  </actor>
  <actor id="/name/nm2525790/">
    <name>Bel Powley</name>
    <dob>1992-3-7</dob>
  </actor>
  <actor id="/name/nm6618353/">
    <name>Ricky Velez</name>
    <dob/>
  </actor>
  <actor id="/name/nm7868231/">
    <name>Lou Wilson</name>
    <dob/>
  </actor>
  <movie id="/title/tt1051906/">
    <year>I</year>
    <title>The Invisible Man</title>
    <genres>
      <genre>Drama</genre>
      <genre>Horror</genre>
      <genre>Mystery</genre>
    </genres>
    <director-ref id="/name/nm1191481/"/>
    <actor-ref id="/name/nm0005253/"/>
    <actor-ref id="/name/nm2719825/"/>
    <actor-ref id="/name/nm2976830/"/>
    <actor-ref id="/name/nm0388038/"/>
  </movie>
  <director id="/name/nm1191481/">
    <name>Leigh Whannell</name>
    <dob>1977-1-17</dob>
  </director>
  <actor id="/name/nm0005253/">
    <name>Elisabeth Moss</name>
    <dob>1982-7-24</dob>
  </actor>
  <actor id="/name/nm2719825/">
    <name>Oliver Jackson-Cohen</name>
    <dob>1986-10-24</dob>
  </actor>
  <actor id="/name/nm2976830/">
    <name>Harriet Dyer</name>
    <dob/>
  </actor>
  <actor id="/name/nm0388038/">
    <name>Aldis Hodge</name>
    <dob>1986-9-20</dob>
  </actor>
  <movie id="/title/tt7504726/">
    <year>2020</year>
    <title>The Call of the Wild</title>
    <genres>
      <genre>Adventure</genre>
      <genre>Drama</genre>
      <genre>Family</genre>
    </genres>
    <director-ref id="/name/nm0761498/"/>
    <actor-ref id="/name/nm0000148/"/>
    <actor-ref id="/name/nm1082477/"/>
    <actor-ref id="/name/nm4446254/"/>
    <actor-ref id="/name/nm1405398/"/>
  </movie>
  <director id="/name/nm0761498/">
    <name>Chris Sanders</name>
    <dob>1962-3-12</dob>
  </director>
  <actor id="/name/nm0000148/">
    <name>Harrison Ford</name>
    <dob>1942-7-13</dob>
  </actor>
  <actor id="/name/nm1082477/">
    <name>Omar Sy</name>
    <dob>1978-1-20</dob>
  </actor>
  <actor id="/name/nm4446254/">
    <name>Cara Gee</name>
    <dob/>
  </actor>
  <actor id="/name/nm1405398/">
    <name>Dan Stevens</name>
    <dob>1982-10-10</dob>
  </actor>
  <movie id="/title/tt8544498/">
    <year>2020</year>
    <title>The Way Back</title>
    <genres>
      <genre>Drama</genre>
      <genre>Sport</genre>
    </genres>
    <director-ref id="/name/nm0640334/"/>
    <actor-ref id="/name/nm0000255/"/>
    <actor-ref id="/name/nm1371339/"/>
    <actor-ref id="/name/nm1232470/"/>
    <actor-ref id="/name/nm1143861/"/>
  </movie>
  <director id="/name/nm0640334/">
    <name>Gavin O'Connor</name>
    <dob>1963-12-24</dob>
  </director>
  <actor id="/name/nm0000255/">
    <name>Ben Affleck</name>
    <dob>1972-8-15</dob>
  </actor>
  <actor id="/name/nm1371339/">
    <name>Al Madrigal</name>
    <dob/>
  </actor>
  <actor id="/name/nm1232470/">
    <name>Janina Gavankar</name>
    <dob>1980-11-29</dob>
  </actor>
  <actor id="/name/nm1143861/">
    <name>Michaela Watkins</name>
    <dob>1971-12-14</dob>
  </actor>
  <movie id="/title/tt9214832/">
    <year>2020</year>
    <title>Emma.</title>
    <genres>
      <genre>Comedy</genre>
      <genre>Drama</genre>
      <genre>Romance</genre>
    </genres>
    <director-ref id="/name/nm2127315/"/>
    <actor-ref id="/name/nm5896355/"/>
    <actor-ref id="/name/nm1926865/"/>
    <actor-ref id="/name/nm5301405/"/>
    <actor-ref id="/name/nm2653929/"/>
  </movie>
  <director id="/name/nm2127315/">
    <name>Autumn de Wilde</name>
    <dob/>
  </director>
  <actor id="/name/nm5896355/">
    <name>Anya Taylor-Joy</name>
    <dob>1996-4-16</dob>
  </actor>
  <actor id="/name/nm1926865/">
    <name>Johnny Flynn</name>
    <dob>1983-3-14</dob>
  </actor>
  <actor id="/name/nm5301405/">
    <name>Mia Goth</name>
    <dob>1993-11-0</dob>
  </actor>
  <actor id="/name/nm2653929/">
    <name>Angus Imrie</name>
    <dob>1994-8-2</dob>
  </actor>
  <movie id="/title/tt1502397/">
    <year>2020</year>
    <title>Bad Boys for Life</title>
    <genres>
      <genre>Action</genre>
      <genre>Comedy</genre>
      <genre>Crime</genre>
    </genres>
    <director-ref id="/name/nm4816401/"/>
    <actor-ref id="/name/nm4263190/"/>
    <actor-ref id="/name/nm0000226/"/>
    <actor-ref id="/name/nm0001454/"/>
    <actor-ref id="/name/nm1227814/"/>
    <actor-ref id="/name/nm1573253/"/>
  </movie>
  <director id="/name/nm4816401/">
    <name>Adil El Arbi</name>
    <dob/>
  </director>
  <actor id="/name/nm4263190/">
    <name>Bilall Fallah</name>
    <dob/>
  </actor>
  <actor id="/name/nm0000226/">
    <name>Will Smith</name>
    <dob>1968-9-25</dob>
  </actor>
  <actor id="/name/nm0001454/">
    <name>Martin Lawrence</name>
    <dob>1965-4-16</dob>
  </actor>
  <actor id="/name/nm1227814/">
    <name>Vanessa Hudgens</name>
    <dob>1988-12-14</dob>
  </actor>
  <actor id="/name/nm1573253/">
    <name>Alexander Ludwig</name>
    <dob>1992-5-7</dob>
  </actor>
  <movie id="/title/tt3794354/">
    <year>2020</year>
    <title>Sonic the Hedgehog</title>
    <genres>
      <genre>Action</genre>
      <genre>Adventure</genre>
      <genre>Comedy</genre>
    </genres>
    <director-ref id="/name/nm1733778/"/>
    <actor-ref id="/name/nm2355635/"/>
    <actor-ref id="/name/nm0005188/"/>
    <actor-ref id="/name/nm0000120/"/>
    <actor-ref id="/name/nm1754366/"/>
  </movie>
  <director id="/name/nm1733778/">
    <name>Jeff Fowler</name>
    <dob>1978-7-27</dob>
  </director>
  <actor id="/name/nm2355635/">
    <name>Ben Schwartz</name>
    <dob>1981-9-15</dob>
  </actor>
  <actor id="/name/nm0005188/">
    <name>James Marsden</name>
    <dob>1973-9-18</dob>
  </actor>
  <actor id="/name/nm0000120/">
    <name>Jim Carrey</name>
    <dob>1962-1-17</dob>
  </actor>
  <actor id="/name/nm1754366/">
    <name>Tika Sumpter</name>
    <dob>1980-6-20</dob>
  </actor>
  <movie id="/title/tt8244784/">
    <year>II</year>
    <title>The Hunt</title>
    <genres>
      <genre>Action</genre>
      <genre>Horror</genre>
      <genre>Thriller</genre>
    </genres>
    <director-ref id="/name/nm0957505/"/>
    <actor-ref id="/name/nm2365811/"/>
    <actor-ref id="/name/nm0005476/"/>
    <actor-ref id="/name/nm0054697/"/>
    <actor-ref id="/name/nm0245145/"/>
  </movie>
  <director id="/name/nm0957505/">
    <name>Craig Zobel</name>
    <dob/>
  </director>
  <actor id="/name/nm2365811/">
    <name>Betty Gilpin</name>
    <dob>1986-7-21</dob>
  </actor>
  <actor id="/name/nm0005476/">
    <name>Hilary Swank</name>
    <dob>1974-7-30</dob>
  </actor>
  <actor id="/name/nm0054697/">
    <name>Ike Barinholtz</name>
    <dob>1977-2-18</dob>
  </actor>
  <actor id="/name/nm0245145/">
    <name>Wayne Duvall</name>
    <dob>1958-5-29</dob>
  </actor>
  <movie id="/title/tt7556122/">
    <year>2020</year>
    <title>The Old Guard</title>
    <genres>
      <genre>Action</genre>
      <genre>Adventure</genre>
      <genre>Fantasy</genre>
    </genres>
    <director-ref id="/name/nm0697656/"/>
    <actor-ref id="/name/nm0000234/"/>
    <actor-ref id="/name/nm8460487/"/>
    <actor-ref id="/name/nm0774386/"/>
    <actor-ref id="/name/nm3092471/"/>
  </movie>
  <director id="/name/nm0697656/">
    <name>Gina Prince-Bythewood</name>
    <dob>1969-6-10</dob>
  </director>
  <actor id="/name/nm0000234/">
    <name>Charlize Theron</name>
    <dob>1975-8-7</dob>
  </actor>
  <actor id="/name/nm8460487/">
    <name>KiKi Layne</name>
    <dob/>
  </actor>
  <actor id="/name/nm0774386/">
    <name>Matthias Schoenaerts</name>
    <dob>1977-12-8</dob>
  </actor>
  <actor id="/name/nm3092471/">
    <name>Marwan Kenzari</name>
    <dob>1983-1-16</dob>
  </actor>
  <movie id="/title/tt7713068/">
    <year>2020</year>
    <title>Birds of Prey: And the Fantabulous Emancipation of One Harley Quinn</title>
    <genres>
      <genre>Action</genre>
      <genre>Adventure</genre>
      <genre>Crime</genre>
    </genres>
    <director-ref id="/name/nm4014166/"/>
    <actor-ref id="/name/nm3053338/"/>
    <actor-ref id="/name/nm0001609/"/>
    <actor-ref id="/name/nm0935541/"/>
    <actor-ref id="/name/nm0810619/"/>
  </movie>
  <director id="/name/nm4014166/">
    <name>Cathy Yan</name>
    <dob/>
  </director>
  <actor id="/name/nm3053338/">
    <name>Margot Robbie</name>
    <dob>1990-7-2</dob>
  </actor>
  <actor id="/name/nm0001609/">
    <name>Rosie Perez</name>
    <dob>1964-9-6</dob>
  </actor>
  <actor id="/name/nm0935541/">
    <name>Mary Elizabeth Winstead</name>
    <dob>1984-11-28</dob>
  </actor>
  <actor id="/name/nm0810619/">
    <name>Jurnee Smollett</name>
    <dob>1986-10-1</dob>
  </actor>
  <movie id="/title/tt8851668/">
    <year>2020</year>
    <title>The Lovebirds</title>
    <genres>
      <genre>Action</genre>
      <genre>Comedy</genre>
      <genre>Crime</genre>
    </genres>
    <director-ref id="/name/nm0795290/"/>
    <actor-ref id="/name/nm4793987/"/>
    <actor-ref id="/name/nm3529685/"/>
    <actor-ref id="/name/nm0817027/"/>
    <actor-ref id="/name/nm2319871/"/>
  </movie>
  <director id="/name/nm0795290/">
    <name>Michael Showalter</name>
    <dob>1970-6-17</dob>
  </director>
  <actor id="/name/nm4793987/">
    <name>Issa Rae</name>
    <dob>1985-1-12</dob>
  </actor>
  <actor id="/name/nm3529685/">
    <name>Kumail Nanjiani</name>
    <dob>1978-2-21</dob>
  </actor>
  <actor id="/name/nm0817027/">
    <name>Paul Sparks</name>
    <dob>1971-10-16</dob>
  </actor>
  <actor id="/name/nm2319871/">
    <name>Anna Camp</name>
    <dob>1982-9-27</dob>
  </actor>
  <movie id="/title/tt5774060/">
    <year>2020</year>
    <title>Underwater</title>
    <genres>
      <genre>Action</genre>
      <genre>Horror</genre>
      <genre>Sci-Fi</genre>
    </genres>
    <director-ref id="/name/nm1827931/"/>
    <actor-ref id="/name/nm0829576/"/>
    <actor-ref id="/name/nm0001993/"/>
    <actor-ref id="/name/nm6974206/"/>
    <actor-ref id="/name/nm2554352/"/>
  </movie>
  <director id="/name/nm1827931/">
    <name>William Eubank</name>
    <dob/>
  </director>
  <actor id="/name/nm0829576/">
    <name>Kristen Stewart</name>
    <dob>1990-4-9</dob>
  </actor>
  <actor id="/name/nm0001993/">
    <name>Vincent Cassel</name>
    <dob>1966-11-23</dob>
  </actor>
  <actor id="/name/nm6974206/">
    <name>Mamoudou Athie</name>
    <dob/>
  </actor>
  <actor id="/name/nm2554352/">
    <name>T.J. Miller</name>
    <dob>1981-6-4</dob>
  </actor>
  <movie id="/title/tt1634106/">
    <year>2020</year>
    <title>Bloodshot</title>
    <genres>
      <genre>Action</genre>
      <genre>Drama</genre>
      <genre>Sci-Fi</genre>
    </genres>
    <director-ref id="/name/nm1702145/"/>
    <actor-ref id="/name/nm0004874/"/>
    <actor-ref id="/name/nm2555462/"/>
    <actor-ref id="/name/nm1537825/"/>
    <actor-ref id="/name/nm1527905/"/>
  </movie>
  <director id="/name/nm1702145/">
    <name>Dave Wilson</name>
    <dob/>
  </director>
  <actor id="/name/nm0004874/">
    <name>Vin Diesel</name>
    <dob>1967-7-18</dob>
  </actor>
  <actor id="/name/nm2555462/">
    <name>Eiza Gonz√°lez</name>
    <dob>1990-1-30</dob>
  </actor>
  <actor id="/name/nm1537825/">
    <name>Sam Heughan</name>
    <dob>1980-4-30</dob>
  </actor>
  <actor id="/name/nm1527905/">
    <name>Toby Kebbell</name>
    <dob>1982-7-9</dob>
  </actor>
  <movie id="/title/tt9048840/">
    <year>2020</year>
    <title>Twelve</title>
    <genres>
      <genre>Drama</genre>
    </genres>
    <director-ref id="/name/nm3924049/"/>
    <actor-ref id="/name/nm8091769/"/>
    <actor-ref id="/name/nm4049674/"/>
    <actor-ref id="/name/nm2825058/"/>
    <actor-ref id="/name/nm5621902/"/>
  </movie>
  <director id="/name/nm3924049/">
    <name>Angel Manuel Soto</name>
    <dob>1983-1-28</dob>
  </director>
  <actor id="/name/nm8091769/">
    <name>Jahi Di'Allo Winston</name>
    <dob/>
  </actor>
  <actor id="/name/nm4049674/">
    <name>Meek Mill</name>
    <dob>1987-5-6</dob>
  </actor>
  <actor id="/name/nm2825058/">
    <name>William Catlett</name>
    <dob/>
  </actor>
  <actor id="/name/nm5621902/">
    <name>Donielle T. Hansley Jr.</name>
    <dob/>
  </actor>
  <movie id="/title/tt9620292/">
    <year>2020</year>
    <title>Promising Young Woman</title>
    <genres>
      <genre>Comedy</genre>
      <genre>Crime</genre>
      <genre>Drama</genre>
    </genres>
    <director-ref id="/name/nm2193504/"/>
    <actor-ref id="/name/nm1659547/"/>
    <actor-ref id="/name/nm3102998/"/>
    <actor-ref id="/name/nm1209545/"/>
    <actor-ref id="/name/nm0000317/"/>
  </movie>
  <director id="/name/nm2193504/">
    <name>Emerald Fennell</name>
    <dob>1985-10-1</dob>
  </director>
  <actor id="/name/nm1659547/">
    <name>Carey Mulligan</name>
    <dob>1985-5-28</dob>
  </actor>
  <actor id="/name/nm3102998/">
    <name>Bo Burnham</name>
    <dob>1990-8-21</dob>
  </actor>
  <actor id="/name/nm1209545/">
    <name>Laverne Cox</name>
    <dob>1972-5-29</dob>
  </actor>
  <actor id="/name/nm0000317/">
    <name>Clancy Brown</name>
    <dob>1959-1-5</dob>
  </actor>
  <movie id="/title/tt7772582/">
    <year>2020</year>
    <title>Never Rarely Sometimes Always</title>
    <genres>
      <genre>Drama</genre>
    </genres>
    <director-ref id="/name/nm2151374/"/>
    <actor-ref id="/name/nm10620978/"/>
    <actor-ref id="/name/nm7867621/"/>
    <actor-ref id="/name/nm6829691/"/>
    <actor-ref id="/name/nm8665872/"/>
  </movie>
  <director id="/name/nm2151374/">
    <name>Eliza Hittman</name>
    <dob/>
  </director>
  <actor id="/name/nm10620978/">
    <name>Sidney Flanigan</name>
    <dob/>
  </actor>
  <actor id="/name/nm7867621/">
    <name>Talia Ryder</name>
    <dob/>
  </actor>
  <actor id="/name/nm6829691/">
    <name>Th√©odore Pellerin</name>
    <dob/>
  </actor>
  <actor id="/name/nm8665872/">
    <name>Eliazar Jimenez</name>
    <dob/>
  </actor>
  <movie id="/title/tt6048922/">
    <year>2020</year>
    <title>Greyhound</title>
    <genres>
      <genre>Action</genre>
      <genre>Drama</genre>
      <genre>History</genre>
    </genres>
    <director-ref id="/name/nm0773689/"/>
    <actor-ref id="/name/nm0000158/"/>
    <actor-ref id="/name/nm0000223/"/>
    <actor-ref id="/name/nm0334318/"/>
    <actor-ref id="/name/nm5090093/"/>
  </movie>
  <director id="/name/nm0773689/">
    <name>Aaron Schneider</name>
    <dob/>
  </director>
  <actor id="/name/nm0000158/">
    <name>Tom Hanks</name>
    <dob>1956-7-9</dob>
  </actor>
  <actor id="/name/nm0000223/">
    <name>Elisabeth Shue</name>
    <dob>1963-10-6</dob>
  </actor>
  <actor id="/name/nm0334318/">
    <name>Stephen Graham</name>
    <dob>1973-8-3</dob>
  </actor>
  <actor id="/name/nm5090093/">
    <name>Matt Helm</name>
    <dob/>
  </actor>
  <movie id="/title/tt0783640/">
    <year>2019</year>
    <title>The Last Full Measure</title>
    <genres>
      <genre>Drama</genre>
      <genre>War</genre>
    </genres>
    <director-ref id="/name/nm0733149/"/>
    <actor-ref id="/name/nm1659221/"/>
    <actor-ref id="/name/nm0837223/"/>
    <actor-ref id="/name/nm8313926/"/>
    <actor-ref id="/name/nm0004986/"/>
  </movie>
  <director id="/name/nm0733149/">
    <name>Todd Robinson</name>
    <dob/>
  </director>
  <actor id="/name/nm1659221/">
    <name>Sebastian Stan</name>
    <dob>1982-8-13</dob>
  </actor>
  <actor id="/name/nm0837223/">
    <name>Alison Sudol</name>
    <dob>1984-12-23</dob>
  </actor>
  <actor id="/name/nm8313926/">
    <name>Asher Miles Fallica</name>
    <dob/>
  </actor>
  <actor id="/name/nm0004986/">
    <name>LisaGay Hamilton</name>
    <dob>1964-3-25</dob>
  </actor>
  <movie id="/title/tt9779516/">
    <year>2020</year>
    <title>I Still Believe</title>
    <genres>
      <genre>Biography</genre>
      <genre>Drama</genre>
      <genre>Music</genre>
    </genres>
    <director-ref id="/name/nm3401779/"/>
    <actor-ref id="/name/nm2296528/"/>
    <actor-ref id="/name/nm6216001/"/>
    <actor-ref id="/name/nm1429380/"/>
    <actor-ref id="/name/nm1452155/"/>
    <actor-ref id="/name/nm0000641/"/>
  </movie>
  <director id="/name/nm3401779/">
    <name>Andrew Erwin</name>
    <dob/>
  </director>
  <actor id="/name/nm2296528/">
    <name>Jon Erwin</name>
    <dob/>
  </actor>
  <actor id="/name/nm6216001/">
    <name>K.J. Apa</name>
    <dob>1997-6-16</dob>
  </actor>
  <actor id="/name/nm1429380/">
    <name>Britt Robertson</name>
    <dob>1990-4-18</dob>
  </actor>
  <actor id="/name/nm1452155/">
    <name>Nathan Parsons</name>
    <dob>1988-6-16</dob>
  </actor>
  <actor id="/name/nm0000641/">
    <name>Gary Sinise</name>
    <dob>1955-3-17</dob>
  </actor>
  <movie id="/title/tt9684220/">
    <year>2020</year>
    <title>Bad Trip</title>
    <genres>
      <genre>Comedy</genre>
    </genres>
    <director-ref id="/name/nm0757318/"/>
    <actor-ref id="/name/nm2765191/"/>
    <actor-ref id="/name/nm2577076/"/>
    <actor-ref id="/name/nm1840504/"/>
    <actor-ref id="/name/nm5006067/"/>
  </movie>
  <director id="/name/nm0757318/">
    <name>Kitao Sakurai</name>
    <dob/>
  </director>
  <actor id="/name/nm2765191/">
    <name>Eric Andr√©</name>
    <dob>1984-4-4</dob>
  </actor>
  <actor id="/name/nm2577076/">
    <name>Lil Rel Howery</name>
    <dob/>
  </actor>
  <actor id="/name/nm1840504/">
    <name>Tiffany Haddish</name>
    <dob>1979-12-3</dob>
  </actor>
  <actor id="/name/nm5006067/">
    <name>Anthony J. James</name>
    <dob/>
  </actor>
  <movie id="/title/tt9883996/">
    <year>2020</year>
    <title>Dream Horse</title>
    <genres>
      <genre>Biography</genre>
      <genre>Comedy</genre>
      <genre>Drama</genre>
    </genres>
    <director-ref id="/name/nm0528186/"/>
    <actor-ref id="/name/nm0001057/"/>
    <actor-ref id="/name/nm0507073/"/>
    <actor-ref id="/name/nm0205749/"/>
    <actor-ref id="/name/nm0268297/"/>
  </movie>
  <director id="/name/nm0528186/">
    <name>Euros Lyn</name>
    <dob>1971-0-0</dob>
  </director>
  <actor id="/name/nm0001057/">
    <name>Toni Collette</name>
    <dob>1972-11-1</dob>
  </actor>
  <actor id="/name/nm0507073/">
    <name>Damian Lewis</name>
    <dob>1971-2-11</dob>
  </actor>
  <actor id="/name/nm0205749/">
    <name>Peter Davison</name>
    <dob>1951-4-13</dob>
  </actor>
  <actor id="/name/nm0268297/">
    <name>Nicholas Farrell</name>
    <dob>1955-0-0</dob>
  </actor>
  <movie id="/title/tt8242084/">
    <year>2020</year>
    <title>My Spy</title>
    <genres>
      <genre>Action</genre>
      <genre>Comedy</genre>
    </genres>
    <director-ref id="/name/nm0781842/"/>
    <actor-ref id="/name/nm1176985/"/>
    <actor-ref id="/name/nm5668548/"/>
    <actor-ref id="/name/nm1406792/"/>
    <actor-ref id="/name/nm1102891/"/>
  </movie>
  <director id="/name/nm0781842/">
    <name>Peter Segal</name>
    <dob>1962-0-0</dob>
  </director>
  <actor id="/name/nm1176985/">
    <name>Dave Bautista</name>
    <dob>1969-1-18</dob>
  </actor>
  <actor id="/name/nm5668548/">
    <name>Chloe Coleman</name>
    <dob>2008-11-23</dob>
  </actor>
  <actor id="/name/nm1406792/">
    <name>Parisa Fitz-Henley</name>
    <dob/>
  </actor>
  <actor id="/name/nm1102891/">
    <name>Kristen Schaal</name>
    <dob>1978-1-24</dob>
  </actor>
  <movie id="/title/tt6587640/">
    <year>2020</year>
    <title>Trolls World Tour</title>
    <genres>
      <genre>Animation</genre>
      <genre>Adventure</genre>
      <genre>Comedy</genre>
    </genres>
    <director-ref id="/name/nm0230666/"/>
    <actor-ref id="/name/nm1019583/"/>
    <actor-ref id="/name/nm0447695/"/>
    <actor-ref id="/name/nm0005493/"/>
    <actor-ref id="/name/nm3417385/"/>
    <actor-ref id="/name/nm0179479/"/>
  </movie>
  <director id="/name/nm0230666/">
    <name>Walt Dohrn</name>
    <dob>1970-12-5</dob>
  </director>
  <actor id="/name/nm1019583/">
    <name>David P. Smith</name>
    <dob>1968-0-0</dob>
  </actor>
  <actor id="/name/nm0447695/">
    <name>Anna Kendrick</name>
    <dob>1985-8-9</dob>
  </actor>
  <actor id="/name/nm0005493/">
    <name>Justin Timberlake</name>
    <dob>1981-1-31</dob>
  </actor>
  <actor id="/name/nm3417385/">
    <name>Rachel Bloom</name>
    <dob>1987-4-3</dob>
  </actor>
  <actor id="/name/nm0179479/">
    <name>James Corden</name>
    <dob>1978-8-22</dob>
  </actor>
  <movie id="/title/tt9308382/">
    <year>2020</year>
    <title>The High Note</title>
    <genres>
      <genre>Drama</genre>
      <genre>Music</genre>
      <genre>Romance</genre>
    </genres>
    <director-ref id="/name/nm0304091/"/>
    <actor-ref id="/name/nm0424848/"/>
    <actor-ref id="/name/nm0743896/"/>
    <actor-ref id="/name/nm5123156/"/>
    <actor-ref id="/name/nm0000597/"/>
  </movie>
  <director id="/name/nm0304091/">
    <name>Nisha Ganatra</name>
    <dob>1971-6-25</dob>
  </director>
  <actor id="/name/nm0424848/">
    <name>Dakota Johnson</name>
    <dob>1989-10-4</dob>
  </actor>
  <actor id="/name/nm0743896/">
    <name>Tracee Ellis Ross</name>
    <dob>1972-10-29</dob>
  </actor>
  <actor id="/name/nm5123156/">
    <name>Kelvin Harrison Jr.</name>
    <dob>1994-7-23</dob>
  </actor>
  <actor id="/name/nm0000597/">
    <name>Bill Pullman</name>
    <dob>1953-12-17</dob>
  </actor>
  <movie id="/title/tt7798646/">
    <year>I</year>
    <title>The Photograph</title>
    <genres>
      <genre>Drama</genre>
      <genre>Romance</genre>
    </genres>
    <director-ref id="/name/nm4907810/"/>
    <actor-ref id="/name/nm4793987/"/>
    <actor-ref id="/name/nm3147751/"/>
    <actor-ref id="/name/nm6001320/"/>
    <actor-ref id="/name/nm5002057/"/>
  </movie>
  <director id="/name/nm4907810/">
    <name>Stella Meghie</name>
    <dob/>
  </director>
  <actor id="/name/nm3147751/">
    <name>LaKeith Stanfield</name>
    <dob>1991-8-12</dob>
  </actor>
  <actor id="/name/nm6001320/">
    <name>Chant√© Adams</name>
    <dob/>
  </actor>
  <actor id="/name/nm5002057/">
    <name>Y'lan Noel</name>
    <dob/>
  </actor>
  <movie id="/title/tt2420124/">
    <year>2020</year>
    <title>Wendy</title>
    <genres>
      <genre>Drama</genre>
      <genre>Fantasy</genre>
    </genres>
    <director-ref id="/name/nm1022455/"/>
    <actor-ref id="/name/nm11293332/"/>
    <actor-ref id="/name/nm11318161/"/>
    <actor-ref id="/name/nm11293333/"/>
    <actor-ref id="/name/nm11293334/"/>
  </movie>
  <director id="/name/nm1022455/">
    <name>Benh Zeitlin</name>
    <dob>1982-10-14</dob>
  </director>
  <actor id="/name/nm11293332/">
    <name>Devin France</name>
    <dob/>
  </actor>
  <actor id="/name/nm11318161/">
    <name>Yashua Mack</name>
    <dob/>
  </actor>
  <actor id="/name/nm11293333/">
    <name>Gage Naquin</name>
    <dob/>
  </actor>
  <actor id="/name/nm11293334/">
    <name>Gavin Naquin</name>
    <dob/>
  </actor>
  <movie id="/title/tt9068272/">
    <year>2020</year>
    <title>First Lady</title>
    <genres>
      <genre>Comedy</genre>
      <genre>Romance</genre>
    </genres>
    <director-ref id="/name/nm0562090/"/>
    <actor-ref id="/name/nm0821328/"/>
    <actor-ref id="/name/nm0000929/"/>
    <actor-ref id="/name/nm0001107/"/>
    <actor-ref id="/name/nm1254478/"/>
  </movie>
  <director id="/name/nm0562090/">
    <name>Nina May</name>
    <dob/>
  </director>
  <actor id="/name/nm0821328/">
    <name>Nancy Stafford</name>
    <dob>1954-6-5</dob>
  </actor>
  <actor id="/name/nm0000929/">
    <name>Corbin Bernsen</name>
    <dob>1954-9-7</dob>
  </actor>
  <actor id="/name/nm0001107/">
    <name>Stacey Dash</name>
    <dob>1967-1-20</dob>
  </actor>
  <actor id="/name/nm1254478/">
    <name>Benjamin Dane</name>
    <dob>1962-7-20</dob>
  </actor>
  <movie id="/title/tt8332922/">
    <year>2020</year>
    <title>A Quiet Place Part II</title>
    <genres>
      <genre>Drama</genre>
      <genre>Horror</genre>
      <genre>Sci-Fi</genre>
    </genres>
    <director-ref id="/name/nm1024677/"/>
    <actor-ref id="/name/nm1289434/"/>
    <actor-ref id="/name/nm8075925/"/>
    <actor-ref id="/name/nm0614165/"/>
    <actor-ref id="/name/nm7415871/"/>
  </movie>
  <director id="/name/nm1024677/">
    <name>John Krasinski</name>
    <dob>1979-10-20</dob>
  </director>
  <actor id="/name/nm1289434/">
    <name>Emily Blunt</name>
    <dob>1983-2-23</dob>
  </actor>
  <actor id="/name/nm8075925/">
    <name>Millicent Simmonds</name>
    <dob>2003-3-1</dob>
  </actor>
  <actor id="/name/nm0614165/">
    <name>Cillian Murphy</name>
    <dob>1976-5-25</dob>
  </actor>
  <actor id="/name/nm7415871/">
    <name>Noah Jupe</name>
    <dob>2005-2-25</dob>
  </actor>
  <movie id="/title/tt4566758/">
    <year>2020</year>
    <title>Mulan</title>
    <genres>
      <genre>Action</genre>
      <genre>Adventure</genre>
      <genre>Drama</genre>
    </genres>
    <director-ref id="/name/nm0138927/"/>
    <actor-ref id="/name/nm1703577/"/>
    <actor-ref id="/name/nm0947447/"/>
    <actor-ref id="/name/nm0000084/"/>
    <actor-ref id="/name/nm0001472/"/>
  </movie>
  <director id="/name/nm0138927/">
    <name>Niki Caro</name>
    <dob>1967-0-0</dob>
  </director>
  <actor id="/name/nm1703577/">
    <name>Yifei Liu</name>
    <dob>1987-8-25</dob>
  </actor>
  <actor id="/name/nm0947447/">
    <name>Donnie Yen</name>
    <dob>1963-7-27</dob>
  </actor>
  <actor id="/name/nm0000084/">
    <name>Li Gong</name>
    <dob>1965-12-31</dob>
  </actor>
  <actor id="/name/nm0001472/">
    <name>Jet Li</name>
    <dob>1963-4-26</dob>
  </actor>
  <movie id="/title/tt8376234/">
    <year>2020</year>
    <title>Peter Rabbit 2</title>
    <genres>
      <genre>Adventure</genre>
      <genre>Comedy</genre>
      <genre>Family</genre>
    </genres>
    <director-ref id="/name/nm0323239/"/>
    <actor-ref id="/name/nm0179479/"/>
    <actor-ref id="/name/nm4456120/"/>
    <actor-ref id="/name/nm0416694/"/>
    <actor-ref id="/name/nm3053338/"/>
  </movie>
  <director id="/name/nm0323239/">
    <name>Will Gluck</name>
    <dob/>
  </director>
  <actor id="/name/nm4456120/">
    <name>Elizabeth Debicki</name>
    <dob>1990-8-24</dob>
  </actor>
  <actor id="/name/nm0416694/">
    <name>Lennie James</name>
    <dob>1965-10-11</dob>
  </actor>
  <movie id="/title/tt4411584/">
    <year>2020</year>
    <title>The Secret: Dare to Dream</title>
    <genres>
      <genre>Drama</genre>
      <genre>Romance</genre>
    </genres>
    <director-ref id="/name/nm0855035/"/>
    <actor-ref id="/name/nm0005017/"/>
    <actor-ref id="/name/nm0524197/"/>
    <actor-ref id="/name/nm0922927/"/>
    <actor-ref id="/name/nm0005278/"/>
  </movie>
  <director id="/name/nm0855035/">
    <name>Andy Tennant</name>
    <dob>1955-6-15</dob>
  </director>
  <actor id="/name/nm0005017/">
    <name>Katie Holmes</name>
    <dob>1978-12-18</dob>
  </actor>
  <actor id="/name/nm0524197/">
    <name>Josh Lucas</name>
    <dob>1971-6-20</dob>
  </actor>
  <actor id="/name/nm0922927/">
    <name>Celia Weston</name>
    <dob>1951-12-14</dob>
  </actor>
  <actor id="/name/nm0005278/">